import type { Metadata } from 'next';
import { Signika_Negative } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import { cn } from '@/libs/utils';
import { Layout } from '@/components/common/Layout';

const inter = Signika_Negative({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'dark')}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
